import { Assets } from "../../../assets/Assets"

export const Books = [
    {
        bookId: 1,
        coverPath: Assets.Images.book1,
        name: 'Book1',
        author: 'Author1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 2,
        coverPath: Assets.Images.book2,
        name: 'Book2',
        author: 'Author2',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 3,
        coverPath: Assets.Images.book3,
        name: 'Book3',
        author: 'Author3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 4,
        coverPath: Assets.Images.book4,
        name: 'Book4',
        author: 'Author4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 5,
        coverPath: Assets.Images.book5,
        name: 'Book5',
        author: 'Author5',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 6,
        coverPath: Assets.Images.book6,
        name: 'Book6',
        author: 'Author6',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 7,
        coverPath: Assets.Images.book7,
        name: 'Book7',
        author: 'Author7',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 8,
        coverPath: Assets.Images.book8,
        name: 'Book8',
        author: 'Author8',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 9,
        coverPath: Assets.Images.book9,
        name: 'Book9',
        author: 'Author9',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 10,
        coverPath: Assets.Images.book10,
        name: 'Book10',
        author: 'Author10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 11,
        coverPath: Assets.Images.book11,
        name: 'Book11',
        author: 'Author11',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 12,
        coverPath: Assets.Images.book12,
        name: 'Book12',
        author: 'Author12',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 13,
        coverPath: Assets.Images.book13,
        name: 'Book13',
        author: 'Author13',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 14,
        coverPath: Assets.Images.book14,
        name: 'Book14',
        author: 'Author14',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 15,
        coverPath: Assets.Images.book15,
        name: 'Book15',
        author: 'Author15',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 16,
        coverPath: Assets.Images.book16,
        name: 'Book16',
        author: 'Author16',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 17,
        coverPath: Assets.Images.book17,
        name: 'Book17',
        author: 'Author17',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 18,
        coverPath: Assets.Images.book18,
        name: 'Book18',
        author: 'Author18',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 19,
        coverPath: Assets.Images.book19,
        name: 'Book19',
        author: 'Author19',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 20,
        coverPath: Assets.Images.book20,
        name: 'Book20',
        author: 'Author20',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },
    {
        bookId: 21,
        coverPath: Assets.Images.book21,
        name: 'Book21',
        author: 'Author21',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip commodo consequat...',
        star: '4.9',    
    },

]