export const ScreenNames = {
    signInScreen: 'SignIn',
    signUpScreen: 'SignUp',
    userHomeScreen: 'Trang chủ',
    userLibrarianScreen: 'Thư viện',
    userProfileScreen: 'UserProfile',
    userQRScreen: 'UserQR',
    calendarScreen: 'Lịch',
    bookScreen: 'Book',
    categoryScreen: 'Thể loại',
    userNotificationScreen: 'Thông báo',
    userSettingScreen: 'Cài đặt',
    libraryInfoScreen: 'Thông tin thư viện',
    bookManagementScreen: 'Sách',
    invoiceManagementScreen: 'Hóa đơn',
    staffQRScreen: 'StaffQR',
    staffSettingScreen: 'StaffSetting',

    // navigator
    userMainNavigator: 'UserMainNavigator',
    userHomeNavigator: 'UserHomeNavigator',
    userProfileNavigator: 'UserProfileNavigator',
    userLibrarianNavigator: 'UserLibrarianNavigator',
    staffMainNavigator: 'StaffMainNavigator',
    staffHomeNavigator: 'StaffHomeNavigator',
}